<?php
//
//namespace Database\Seeders;
//
//use App\Models\Employer\Employer;
//use App\Models\Industry;
//use App\Models\Vacancies\Vacancy;
//use Illuminate\Database\Seeder;
//
//class VacancySeeder extends Seeder
//{
//    public function run(): void
//    {
//        // Ensure industries exist
//        $industries = [
//            ['name' => 'Информационные технологии (IT)', 'slug' => 'it'],
//            ['name' => 'Образование', 'slug' => 'education'],
//            ['name' => 'Здравоохранение', 'slug' => 'healthcare'],
//            ['name' => 'Строительство', 'slug' => 'construction'],
//            ['name' => 'Финансы и бухгалтерия', 'slug' => 'finance&accounting'],
//            ['name' => 'Производство', 'slug' => 'production'],
//            ['name' => 'Логистика и транспорт', 'slug' => 'logistics&transport'],
//            ['name' => 'Маркетинг и реклама', 'slug' => 'marketing&ads'],
//            ['name' => 'Сельское хозяйство', 'slug' => 'agricultural'],
//            ['name' => 'Туризм и гостиницы', 'slug' => 'tourism&hotels'],
//            ['name' => 'Государственная служба', 'slug' => 'public_service'],
//            ['name' => 'Другое', 'slug' => 'other'],
//        ];
//
//        foreach ($industries as $industry) {
//            Industry::firstOrCreate(['slug' => $industry['slug']], ['name' => $industry['name']]);
//        }
//
//        // Create 7 employers
//        $employers = [
//            [
//                'user_id' => 1,
//                'type' => 'company',
//                'company_name' => 'Tajik IT Solutions',
//                'company_address' => 'г. Душанбе, ул. Рудаки 45',
//                'company_website' => 'https://tajikitsolutions.tj',
//                'description' => 'IT-компания, специализирующаяся на разработке программного обеспечения.',
//                'contact_email' => 'info@tajikitsolutions.tj',
//                'contact_phone' => '+992123456789',
//            ],
//            [
//                'user_id' => 2,
//                'type' => 'company',
//                'company_name' => 'Pamir Education Center',
//                'company_address' => 'г. Худжанд, ул. Ленина 12',
//                'company_website' => 'https://pamireducation.tj',
//                'description' => 'Образовательный центр для школьников и взрослых.',
//                'contact_email' => 'contact@pamireducation.tj',
//                'contact_phone' => '+992987654321',
//            ],
//            [
//                'user_id' => 3,
//                'type' => 'company',
//                'company_name' => 'Sihat Medical Clinic',
//                'company_address' => 'г. Куляб, ул. Сомони 23',
//                'company_website' => 'https://sihatclinic.tj',
//                'description' => 'Медицинская клиника, предоставляющая услуги в сельской местности.',
//                'contact_email' => 'info@sihatclinic.tj',
//                'contact_phone' => '+992112233445',
//            ],
//            [
//                'user_id' => 4,
//                'type' => 'company',
//                'company_name' => 'Bunyod Construction',
//                'company_address' => 'г. Бохтар, ул. Айни 10',
//                'company_website' => 'https://bunyodconstruction.tj',
//                'description' => 'Строительная компания, специализирующаяся на жилых объектах.',
//                'contact_email' => 'bunyod@bunyod.tj',
//                'contact_phone' => '+992223344556',
//            ],
//            [
//                'user_id' => 5,
//                'type' => 'company',
//                'company_name' => 'Somoni Finance',
//                'company_address' => 'г. Душанбе, ул. Нисор 15',
//                'company_website' => 'https://somonifinance.tj',
//                'description' => 'Финансовая компания, предоставляющая услуги учета и консалтинга.',
//                'contact_email' => 'info@somonifinance.tj',
//                'contact_phone' => '+992334455667',
//            ],
//            [
//                'user_id' => 6,
//                'type' => 'company',
//                'company_name' => 'Tajik Agro Co',
//                'company_address' => 'г. Гиссар, ул. Фирдавси 8',
//                'company_website' => 'https://tajikagro.tj',
//                'description' => 'Сельскохозяйственная компания, занимающаяся выращиванием культур.',
//                'contact_email' => 'agro@tajikagro.tj',
//                'contact_phone' => '+992445566778',
//            ],
//            [
//                'user_id' => 7,
//                'type' => 'company',
//                'company_name' => 'Pamir Travel',
//                'company_address' => 'г. Хорог, ул. Памир 5',
//                'company_website' => 'https://pamirtravel.tj',
//                'description' => 'Туристическая компания, организующая туры по Памиру.',
//                'contact_email' => 'travel@pamirtravel.tj',
//                'contact_phone' => '+992556677889',
//            ],
//        ];
//
//        $employerIds = [];
//        foreach ($employers as $employerData) {
//            $employer = Employer::firstOrCreate(
//                ['user_id' => $employerData['user_id']],
//                $employerData
//            );
//            $employerIds[] = $employer->id;
//        }
//
//        // Create 20 vacancies distributed across 7 employers
//        $vacancies = [
//            // Employer 1: Tajik IT Solutions (3 vacancies)
//            [
//                'employer_id' => $employerIds[0],
//                'title' => 'Программист 1С',
//                'salary_type' => 'money',
//                'salary_start' => 3000,
//                'salary_end' => 5000,
//                'location' => 'Душанбе',
//                'industry_id' => Industry::where('slug', 'it')->first()->id,
//                'description' => 'Настройка и поддержка программ 1С для местных компаний.',
//                'benefits' => 'Обучение, стабильная зарплата, работа в офисе.',
//                'responsibility' => 'Настройка 1С, обучение пользователей, техническая поддержка.',
//                'qualifications' => 'Знание 1С, базовые навыки программирования, знание таджикского и русского языков.',
//                'experience' => '1 год',
//                'education' => 'Среднее специальное',
//                'skills' => (['1С', 'Программирование', 'Техподдержка']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[0],
//                'title' => 'Технический специалист по IT',
//                'salary_type' => 'money',
//                'salary_start' => 2500,
//                'salary_end' => 4000,
//                'location' => 'Душанбе',
//                'industry_id' => Industry::where('slug', 'it')->first()->id,
//                'description' => 'Обслуживание компьютерной техники и сетей в офисе.',
//                'benefits' => 'Обучение, стабильная зарплата.',
//                'responsibility' => 'Настройка оборудования, устранение неполадок.',
//                'qualifications' => 'Знание сетей, базовые навыки администрирования.',
//                'experience' => '2 года',
//                'education' => 'Среднее специальное',
//                'skills' => (['Сетевое администрирование', 'Техподдержка']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[0],
//                'title' => 'Веб-разработчик',
//                'salary_type' => 'money',
//                'salary_start' => 3500,
//                'salary_end' => 5500,
//                'location' => 'Душанбе',
//                'industry_id' => Industry::where('slug', 'it')->first()->id,
//                'description' => 'Разработка веб-сайтов для местных компаний.',
//                'benefits' => 'Гибкий график, бонусы за проекты.',
//                'responsibility' => 'Создание и поддержка веб-сайтов, работа с клиентами.',
//                'qualifications' => 'Знание HTML, CSS, JavaScript, знание таджикского языка.',
//                'experience' => '2 года',
//                'education' => 'Высшее техническое',
//                'skills' => (['HTML', 'CSS', 'JavaScript']),
//                'type' => 'remote',
//                'status' => 'active',
//            ],
//            // Employer 2: Pamir Education Center (3 vacancies)
//            [
//                'employer_id' => $employerIds[1],
//                'title' => 'Учитель таджикского языка',
//                'salary_type' => 'money',
//                'salary_start' => 1500,
//                'salary_end' => 2500,
//                'location' => 'Худжанд',
//                'industry_id' => Industry::where('slug', 'education')->first()->id,
//                'description' => 'Преподавание таджикского языка и литературы в образовательном центре.',
//                'benefits' => 'Длинный отпуск, социальный пакет.',
//                'responsibility' => 'Проведение уроков, подготовка к экзаменам.',
//                'qualifications' => 'Знание таджикского языка, педагогическое образование.',
//                'experience' => 'Без опыта',
//                'education' => 'Высшее педагогическое',
//                'skills' => (['Таджикский язык', 'Преподавание']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[1],
//                'title' => 'Учитель математики',
//                'salary_type' => 'money',
//                'salary_start' => 1500,
//                'salary_end' => 2500,
//                'location' => 'Худжанд',
//                'industry_id' => Industry::where('slug', 'education')->first()->id,
//                'description' => 'Преподавание математики для школьников.',
//                'benefits' => 'Длинный отпуск, стабильный график.',
//                'responsibility' => 'Проведение уроков, подготовка к экзаменам.',
//                'qualifications' => 'Педагогическое образование, знание математики.',
//                'experience' => 'Без опыта',
//                'education' => 'Высшее педагогическое',
//                'skills' => (['Математика', 'Преподавание']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[1],
//                'title' => 'Преподаватель английского языка',
//                'salary_type' => 'money',
//                'salary_start' => 2000,
//                'salary_end' => 3000,
//                'location' => 'Худжанд',
//                'industry_id' => Industry::where('slug', 'education')->first()->id,
//                'description' => 'Преподавание английского языка для взрослых и детей.',
//                'benefits' => 'Гибкий график, учебные материалы.',
//                'responsibility' => 'Проведение занятий, подготовка материалов.',
//                'qualifications' => 'Знание английского языка (B2+), педагогические навыки.',
//                'experience' => '1 год',
//                'education' => 'Высшее',
//                'skills' => (['Английский язык', 'Преподавание']),
//                'type' => 'part',
//                'status' => 'active',
//            ],
//            // Employer 3: Sihat Medical Clinic (3 vacancies)
//            [
//                'employer_id' => $employerIds[2],
//                'title' => 'Фельдшер',
//                'salary_type' => 'money',
//                'salary_start' => 2000,
//                'salary_end' => 3000,
//                'location' => 'Куляб',
//                'industry_id' => Industry::where('slug', 'healthcare')->first()->id,
//                'description' => 'Оказание первой медицинской помощи в сельской клинике.',
//                'benefits' => 'Жилье, транспорт до работы.',
//                'responsibility' => 'Проведение осмотров, оказание первой помощи.',
//                'qualifications' => 'Медицинское образование, сертификат фельдшера.',
//                'experience' => '1 год',
//                'education' => 'Среднее медицинское',
//                'skills' => (['Первая помощь', 'Медицинский уход']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[2],
//                'title' => 'Медсестра/Медбрат',
//                'salary_type' => 'money',
//                'salary_start' => 1800,
//                'salary_end' => 2500,
//                'location' => 'Куляб',
//                'industry_id' => Industry::where('slug', 'healthcare')->first()->id,
//                'description' => 'Уход за пациентами в больнице.',
//                'benefits' => 'Сменный график, соцпакет.',
//                'responsibility' => 'Проведение процедур, помощь врачам.',
//                'qualifications' => 'Медицинское образование, сертификат.',
//                'experience' => '1 год',
//                'education' => 'Среднее медицинское',
//                'skills' => (['Медицинские процедуры', 'Уход за пациентами']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[2],
//                'title' => 'Администратор клиники',
//                'salary_type' => 'money',
//                'salary_start' => 2000,
//                'salary_end' => 3000,
//                'location' => 'Куляб',
//                'industry_id' => Industry::where('slug', 'healthcare')->first()->id,
//                'description' => 'Организация работы медицинской клиники.',
//                'benefits' => 'Стабильная зарплата, соцпакет.',
//                'responsibility' => 'Прием пациентов, ведение документации.',
//                'qualifications' => 'Навыки общения, знание таджикского и русского языков.',
//                'experience' => 'Без опыта',
//                'education' => 'Среднее',
//                'skills' => (['Администрирование', 'Обслуживание клиентов']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            // Employer 4: Bunyod Construction (3 vacancies)
//            [
//                'employer_id' => $employerIds[3],
//                'title' => 'Бригадир строительной бригады',
//                'salary_type' => 'money',
//                'salary_start' => 3500,
//                'salary_end' => 5000,
//                'location' => 'Бохтар',
//                'industry_id' => Industry::where('slug', 'construction')->first()->id,
//                'description' => 'Руководство строительной бригадой на объектах.',
//                'benefits' => 'Жилье на объекте, питание.',
//                'responsibility' => 'Координация рабочих, контроль качества строительства.',
//                'qualifications' => 'Опыт в строительстве, организаторские навыки.',
//                'experience' => '3 года',
//                'education' => 'Среднее',
//                'skills' => (['Строительство', 'Управление бригадой']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[3],
//                'title' => 'Каменщик',
//                'salary_type' => 'money',
//                'salary_start' => 2500,
//                'salary_end' => 3500,
//                'location' => 'Бохтар',
//                'industry_id' => Industry::where('slug', 'construction')->first()->id,
//                'description' => 'Кладка кирпича и блоков на стройке.',
//                'benefits' => 'Жилье, питание.',
//                'responsibility' => 'Выполнение кладочных работ, соблюдение сроков.',
//                'qualifications' => 'Опыт в кладке, физическая выносливость.',
//                'experience' => '2 года',
//                'education' => 'Среднее',
//                'skills' => (['Кладка', 'Строительство']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[3],
//                'title' => 'Разнорабочий на стройке',
//                'salary_type' => 'money',
//                'salary_start' => 1500,
//                'salary_end' => 2000,
//                'location' => 'Бохтар',
//                'industry_id' => Industry::where('slug', 'construction')->first()->id,
//                'description' => 'Выполнение подсобных работ на строительной площадке.',
//                'benefits' => 'Жилье, питание.',
//                'responsibility' => 'Помощь в строительных работах, уборка территории.',
//                'qualifications' => 'Физическая выносливость.',
//                'experience' => 'Без опыта',
//                'education' => 'Среднее',
//                'skills' => (['Физическая работа', 'Строительство']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            // Employer 5: Somoni Finance (3 vacancies)
//            [
//                'employer_id' => $employerIds[4],
//                'title' => 'Бухгалтер на первичную документацию',
//                'salary_type' => 'money',
//                'salary_start' => 2000,
//                'salary_end' => 3000,
//                'location' => 'Душанбе',
//                'industry_id' => Industry::where('slug', 'finance&accounting')->first()->id,
//                'description' => 'Ведение первичной бухгалтерской документации.',
//                'benefits' => 'Стабильная зарплата, обучение.',
//                'responsibility' => 'Обработка счетов, работа в 1С.',
//                'qualifications' => 'Базовое знание бухгалтерии, владение 1С.',
//                'experience' => '1 год',
//                'education' => 'Среднее специальное',
//                'skills' => (['1С', 'Бухучет']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[4],
//                'title' => 'Финансовый консультант',
//                'salary_type' => 'money',
//                'salary_start' => 2500,
//                'salary_end' => 4000,
//                'location' => 'Душанбе',
//                'industry_id' => Industry::where('slug', 'finance&accounting')->first()->id,
//                'description' => 'Консультации по финансовому планированию для местных клиентов.',
//                'benefits' => 'Бонусы за результаты, обучение.',
//                'responsibility' => 'Работа с клиентами, анализ финансов.',
//                'qualifications' => 'Знание финансов, навыки общения, знание таджикского языка.',
//                'experience' => '2 года',
//                'education' => 'Высшее экономическое',
//                'skills' => (['Финансовое планирование', 'Консультации']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[4],
//                'title' => 'Кассир',
//                'salary_type' => 'money',
//                'salary_start' => 1500,
//                'salary_end' => 2000,
//                'location' => 'Душанбе',
//                'industry_id' => Industry::where('slug', 'finance&accounting')->first()->id,
//                'description' => 'Работа с наличными и безналичными платежами.',
//                'benefits' => 'Стабильная зарплата, сменный график.',
//                'responsibility' => 'Прием и выдача денег, ведение кассовой документации.',
//                'qualifications' => 'Навыки работы с кассой, знание таджикского языка.',
//                'experience' => 'Без опыта',
//                'education' => 'Среднее',
//                'skills' => (['Кассовая дисциплина', 'Работа с клиентами']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            // Employer 6: Tajik Agro Co (3 vacancies)
//            [
//                'employer_id' => $employerIds[5],
//                'title' => 'Фермер-агроном',
//                'salary_type' => 'money',
//                'salary_start' => 2000,
//                'salary_end' => 3000,
//                'location' => 'Гиссар',
//                'industry_id' => Industry::where('slug', 'agricultural')->first()->id,
//                'description' => 'Выращивание сельскохозяйственных культур.',
//                'benefits' => 'Жилье, питание.',
//                'responsibility' => 'Уход за посевами, сбор урожая.',
//                'qualifications' => 'Опыт в сельском хозяйстве, знание таджикского языка.',
//                'experience' => '2 года',
//                'education' => 'Среднее',
//                'skills' => (['Сельское хозяйство', 'Агрономия']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[5],
//                'title' => 'Работник фермы',
//                'salary_type' => 'money',
//                'salary_start' => 1500,
//                'salary_end' => 2000,
//                'location' => 'Гиссар',
//                'industry_id' => Industry::where('slug', 'agricultural')->first()->id,
//                'description' => 'Работа на ферме по уходу за растениями и животными.',
//                'benefits' => 'Жилье, питание.',
//                'responsibility' => 'Полив, уход за животными, уборка.',
//                'qualifications' => 'Физическая выносливость.',
//                'experience' => 'Без опыта',
//                'education' => 'Среднее',
//                'skills' => ['Сельское хозяйство', 'Физическая работа'],
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[5],
//                'title' => 'Тракторист',
//                'salary_type' => 'money',
//                'salary_start' => 2000,
//                'salary_end' => 3000,
//                'location' => 'Гиссар',
//                'industry_id' => Industry::where('slug', 'agricultural')->first()->id,
//                'description' => 'Работа на тракторе для обработки полей.',
//                'benefits' => 'Жилье, питание.',
//                'responsibility' => 'Обработка полей, обслуживание техники.',
//                'qualifications' => 'Удостоверение тракториста, опыт работы.',
//                'experience' => '1 год',
//                'education' => 'Среднее',
//                'skills' => (['Трактор', 'Сельское хозяйство']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            // Employer 7: Pamir Travel (2 vacancies)
//            [
//                'employer_id' => $employerIds[6],
//                'title' => 'Администратор гостевого дома',
//                'salary_type' => 'money',
//                'salary_start' => 1500,
//                'salary_end' => 2500,
//                'location' => 'Хорог',
//                'industry_id' => Industry::where('slug', 'tourism&hotels')->first()->id,
//                'description' => 'Обслуживание гостей в гостевом доме на Памире.',
//                'benefits' => 'Проживание, питание.',
//                'responsibility' => 'Прием гостей, организация их пребывания.',
//                'qualifications' => 'Знание таджикского и русского языков, гостеприимство.',
//                'experience' => 'Без опыта',
//                'education' => 'Среднее',
//                'skills' => (['Гостеприимство', 'Обслуживание клиентов']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            [
//                'employer_id' => $employerIds[6],
//                'title' => 'Гид по Памиру',
//                'salary_type' => 'money',
//                'salary_start' => 2000,
//                'salary_end' => 3500,
//                'location' => 'Хорог',
//                'industry_id' => Industry::where('slug', 'tourism&hotels')->first()->id,
//                'description' => 'Проведение экскурсий по Памирским горам.',
//                'benefits' => 'Проживание, питание, бонусы за туры.',
//                'responsibility' => 'Проведение экскурсий, обеспечение безопасности туристов.',
//                'qualifications' => 'Знание английского или русского, навыки общения.',
//                'experience' => '1 год',
//                'education' => 'Среднее',
//                'skills' => (['Экскурсии', 'Коммуникация']),
//                'type' => 'part',
//                'status' => 'active',
//            ],
//            // Additional vacancy for 'public_service' industry
//            [
//                'employer_id' => $employerIds[4],
//                'title' => 'Специалист по госзакупкам',
//                'salary_type' => 'money',
//                'salary_start' => 2500,
//                'salary_end' => 3500,
//                'location' => 'Душанбе',
//                'industry_id' => Industry::where('slug', 'public_service')->first()->id,
//                'description' => 'Организация закупок для государственных учреждений.',
//                'benefits' => 'Стабильная зарплата, соцпакет.',
//                'responsibility' => 'Подготовка документации, участие в тендерах.',
//                'qualifications' => 'Знание законодательства о закупках, знание таджикского языка.',
//                'experience' => '2 года',
//                'education' => 'Высшее',
//                'skills' => (['Госзакупки', 'Документооборот']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//            // Additional vacancy for 'other' industry
//            [
//                'employer_id' => $employerIds[6],
//                'title' => 'Портной',
//                'salary_type' => 'money',
//                'salary_start' => 1500,
//                'salary_end' => 2500,
//                'location' => 'Хорог',
//                'industry_id' => Industry::where('slug', 'other')->first()->id,
//                'description' => 'Пошив национальной одежды и ремонт одежды.',
//                'benefits' => 'Гибкий график, материалы предоставляются.',
//                'responsibility' => 'Пошив, ремонт одежды, работа с клиентами.',
//                'qualifications' => 'Навыки шитья, аккуратность.',
//                'experience' => '1 год',
//                'education' => 'Среднее',
//                'skills' => (['Шитье', 'Работа с клиентами']),
//                'type' => 'full',
//                'status' => 'active',
//            ],
//        ];
//
//        foreach ($vacancies as $vacancy) {
//            Vacancy::create($vacancy);
//        }
//    }
//}


namespace Database\Seeders;

use App\Models\Employer\Employer;
use App\Models\Industry;
use App\Models\Vacancies\Vacancy;
use Illuminate\Database\Seeder;

class VacancySeeder extends Seeder
{
    public function run(): void
    {
        // Ensure industries exist
        $industries = [
            ['name' => 'Информационные технологии (IT)', 'slug' => 'it'],
            ['name' => 'Образование', 'slug' => 'education'],
            ['name' => 'Здравоохранение', 'slug' => 'healthcare'],
            ['name' => 'Строительство', 'slug' => 'construction'],
            ['name' => 'Финансы и бухгалтерия', 'slug' => 'finance&accounting'],
            ['name' => 'Производство', 'slug' => 'production'],
            ['name' => 'Логистика и транспорт', 'slug' => 'logistics&transport'],
            ['name' => 'Маркетинг и реклама', 'slug' => 'marketing&ads'],
            ['name' => 'Сельское хозяйство', 'slug' => 'agricultural'],
            ['name' => 'Туризм и гостиницы', 'slug' => 'tourism&hotels'],
            ['name' => 'Государственная служба', 'slug' => 'public_service'],
            ['name' => 'Другое', 'slug' => 'other'],
        ];

        foreach ($industries as $industry) {
            Industry::firstOrCreate(['slug' => $industry['slug']], ['name' => $industry['name']]);
        }

        // Create 30 employers
        $employerCompanies = [
            ['name' => 'Tajik IT Solutions', 'location' => 'Душанбе', 'website' => 'https://tajikitsolutions.tj'],
            ['name' => 'Pamir Education Center', 'location' => 'Худжанд', 'website' => 'https://pamireducation.tj'],
            ['name' => 'Sihat Medical Clinic', 'location' => 'Куляб', 'website' => 'https://sihatclinic.tj'],
            ['name' => 'Bunyod Construction', 'location' => 'Бохтар', 'website' => 'https://bunyodconstruction.tj'],
            ['name' => 'Somoni Finance', 'location' => 'Душанбе', 'website' => 'https://somonifinance.tj'],
            ['name' => 'Tajik Agro Co', 'location' => 'Гиссар', 'website' => 'https://tajikagro.tj'],
            ['name' => 'Pamir Travel', 'location' => 'Хорог', 'website' => 'https://pamirtravel.tj'],
            ['name' => 'Dushanbe Tech Hub', 'location' => 'Душанбе', 'website' => 'https://dushanbetech.tj'],
            ['name' => 'Khujand Learning', 'location' => 'Худжанд', 'website' => 'https://khujandlearning.tj'],
            ['name' => 'Medical Plus', 'location' => 'Душанбе', 'website' => 'https://medicalplus.tj'],
            ['name' => 'Build Master', 'location' => 'Куляб', 'website' => 'https://buildmaster.tj'],
            ['name' => 'Finance Expert', 'location' => 'Худжанд', 'website' => 'https://financeexpert.tj'],
            ['name' => 'Agro Plus', 'location' => 'Бохтар', 'website' => 'https://agroplus.tj'],
            ['name' => 'Tourism Tajik', 'location' => 'Хорог', 'website' => 'https://tourismtajik.tj'],
            ['name' => 'IT Services Pro', 'location' => 'Душанбе', 'website' => 'https://itservicespro.tj'],
            ['name' => 'Education Center Elite', 'location' => 'Гиссар', 'website' => 'https://educationelite.tj'],
            ['name' => 'Health Care Tajik', 'location' => 'Пенджикент', 'website' => 'https://healthcaretajik.tj'],
            ['name' => 'Construction Pro', 'location' => 'Курган-Тюбе', 'website' => 'https://constructionpro.tj'],
            ['name' => 'Banking Solutions', 'location' => 'Душанбе', 'website' => 'https://bankingsolutions.tj'],
            ['name' => 'Farm Tech', 'location' => 'Рашт', 'website' => 'https://farmtech.tj'],
            ['name' => 'Travel Adventures', 'location' => 'Исфара', 'website' => 'https://traveladventures.tj'],
            ['name' => 'Code Factory', 'location' => 'Душанбе', 'website' => 'https://codefactory.tj'],
            ['name' => 'Teaching Excellence', 'location' => 'Худжанд', 'website' => 'https://teachingexcellence.tj'],
            ['name' => 'Clinical Services', 'location' => 'Куляб', 'website' => 'https://clinicalservices.tj'],
            ['name' => 'Building Future', 'location' => 'Душанбе', 'website' => 'https://buildingfuture.tj'],
            ['name' => 'Accounting Plus', 'location' => 'Худжанд', 'website' => 'https://accountingplus.tj'],
            ['name' => 'Agricultural Solutions', 'location' => 'Гиссар', 'website' => 'https://agriculturesolutions.tj'],
            ['name' => 'Hotel Services', 'location' => 'Хорог', 'website' => 'https://hotelservices.tj'],
            ['name' => 'Digital Agency', 'location' => 'Душанбе', 'website' => 'https://digitalagency.tj'],
            ['name' => 'Training Center Pro', 'location' => 'Бохтар', 'website' => 'https://trainingcenterpro.tj'],
        ];

        $employerIds = [];
        foreach ($employerCompanies as $index => $companyData) {
            $userId = $index + 1;
            $employer = Employer::firstOrCreate(
                ['user_id' => $userId],
                [
                    'user_id' => $userId,
                    'type' => 'company',
                    'company_name' => $companyData['name'],
                    'company_address' => 'г. ' . $companyData['location'] . ', ул. Рудаки ' . rand(1, 100),
                    'company_website' => $companyData['website'],
                    'description' => 'Компания ' . $companyData['name'] . ', работающая в различных сферах.',
                    'contact_email' => strtolower(str_replace(' ', '', $companyData['name'])) . '@example.tj',
                    'contact_phone' => '+992' . rand(100000000, 999999999),
                ]
            );
            $employerIds[] = $employer->id;
        }

        // Vacancy templates for different industries
        $vacancyTemplates = [
            // IT vacancies (4 templates)
            [
                'title' => 'Программист 1С',
                'industry_slug' => 'it',
                'salary_start' => 3000,
                'salary_end' => 5000,
                'description' => 'Настройка и поддержка программ 1С для местных компаний.',
                'benefits' => 'Обучение, стабильная зарплата, работа в офисе.',
                'responsibility' => 'Настройка 1С, обучение пользователей, техническая поддержка.',
                'qualifications' => 'Знание 1С, базовые навыки программирования.',
                'experience' => '1 год',
                'education' => 'Среднее специальное',
                'skills' => ['1С', 'Программирование', 'Техподдержка'],
                'type' => 'full',
            ],
            [
                'title' => 'Веб-разработчик',
                'industry_slug' => 'it',
                'salary_start' => 3500,
                'salary_end' => 5500,
                'description' => 'Разработка веб-сайтов для местных компаний.',
                'benefits' => 'Гибкий график, бонусы за проекты.',
                'responsibility' => 'Создание и поддержка веб-сайтов, работа с клиентами.',
                'qualifications' => 'Знание HTML, CSS, JavaScript.',
                'experience' => '2 года',
                'education' => 'Высшее техническое',
                'skills' => ['HTML', 'CSS', 'JavaScript'],
                'type' => 'remote',
            ],
            [
                'title' => 'Системный администратор',
                'industry_slug' => 'it',
                'salary_start' => 2500,
                'salary_end' => 4000,
                'description' => 'Обслуживание компьютерной техники и сетей.',
                'benefits' => 'Обучение, стабильная зарплата.',
                'responsibility' => 'Настройка оборудования, устранение неполадок.',
                'qualifications' => 'Знание сетей, навыки администрирования.',
                'experience' => '2 года',
                'education' => 'Среднее специальное',
                'skills' => ['Сетевое администрирование', 'Техподдержка'],
                'type' => 'full',
            ],
            [
                'title' => 'Python разработчик',
                'industry_slug' => 'it',
                'salary_start' => 4000,
                'salary_end' => 6000,
                'description' => 'Разработка backend приложений на Python.',
                'benefits' => 'Удалённая работа, гибкий график.',
                'responsibility' => 'Разработка API, работа с базами данных.',
                'qualifications' => 'Знание Python, Django/Flask.',
                'experience' => '3 года',
                'education' => 'Высшее техническое',
                'skills' => ['Python', 'Django', 'PostgreSQL'],
                'type' => 'remote',
            ],
            // Education vacancies (4 templates)
            [
                'title' => 'Учитель таджикского языка',
                'industry_slug' => 'education',
                'salary_start' => 1500,
                'salary_end' => 2500,
                'description' => 'Преподавание таджикского языка и литературы.',
                'benefits' => 'Длинный отпуск, социальный пакет.',
                'responsibility' => 'Проведение уроков, подготовка к экзаменам.',
                'qualifications' => 'Знание таджикского языка, педагогическое образование.',
                'experience' => 'Без опыта',
                'education' => 'Высшее педагогическое',
                'skills' => ['Таджикский язык', 'Преподавание'],
                'type' => 'full',
            ],
            [
                'title' => 'Учитель математики',
                'industry_slug' => 'education',
                'salary_start' => 1500,
                'salary_end' => 2500,
                'description' => 'Преподавание математики для школьников.',
                'benefits' => 'Длинный отпуск, стабильный график.',
                'responsibility' => 'Проведение уроков, подготовка к экзаменам.',
                'qualifications' => 'Педагогическое образование, знание математики.',
                'experience' => 'Без опыта',
                'education' => 'Высшее педагогическое',
                'skills' => ['Математика', 'Преподавание'],
                'type' => 'full',
            ],
            [
                'title' => 'Преподаватель английского языка',
                'industry_slug' => 'education',
                'salary_start' => 2000,
                'salary_end' => 3000,
                'description' => 'Преподавание английского языка для взрослых и детей.',
                'benefits' => 'Гибкий график, учебные материалы.',
                'responsibility' => 'Проведение занятий, подготовка материалов.',
                'qualifications' => 'Знание английского языка (B2+).',
                'experience' => '1 год',
                'education' => 'Высшее',
                'skills' => ['Английский язык', 'Преподавание'],
                'type' => 'part',
            ],
            [
                'title' => 'Воспитатель детского сада',
                'industry_slug' => 'education',
                'salary_start' => 1200,
                'salary_end' => 2000,
                'description' => 'Работа с детьми дошкольного возраста.',
                'benefits' => 'Социальный пакет, отпуск.',
                'responsibility' => 'Уход за детьми, проведение развивающих занятий.',
                'qualifications' => 'Педагогическое образование.',
                'experience' => 'Без опыта',
                'education' => 'Среднее специальное',
                'skills' => ['Работа с детьми', 'Педагогика'],
                'type' => 'full',
            ],
            // Healthcare vacancies (4 templates)
            [
                'title' => 'Фельдшер',
                'industry_slug' => 'healthcare',
                'salary_start' => 2000,
                'salary_end' => 3000,
                'description' => 'Оказание первой медицинской помощи.',
                'benefits' => 'Жилье, транспорт до работы.',
                'responsibility' => 'Проведение осмотров, оказание первой помощи.',
                'qualifications' => 'Медицинское образование, сертификат фельдшера.',
                'experience' => '1 год',
                'education' => 'Среднее медицинское',
                'skills' => ['Первая помощь', 'Медицинский уход'],
                'type' => 'full',
            ],
            [
                'title' => 'Медсестра/Медбрат',
                'industry_slug' => 'healthcare',
                'salary_start' => 1800,
                'salary_end' => 2500,
                'description' => 'Уход за пациентами в больнице.',
                'benefits' => 'Сменный график, соцпакет.',
                'responsibility' => 'Проведение процедур, помощь врачам.',
                'qualifications' => 'Медицинское образование, сертификат.',
                'experience' => '1 год',
                'education' => 'Среднее медицинское',
                'skills' => ['Медицинские процедуры', 'Уход за пациентами'],
                'type' => 'full',
            ],
            [
                'title' => 'Врач общей практики',
                'industry_slug' => 'healthcare',
                'salary_start' => 3500,
                'salary_end' => 5000,
                'description' => 'Прием и лечение пациентов.',
                'benefits' => 'Социальный пакет, обучение.',
                'responsibility' => 'Диагностика, назначение лечения.',
                'qualifications' => 'Высшее медицинское образование, лицензия.',
                'experience' => '3 года',
                'education' => 'Высшее',
                'skills' => ['Диагностика', 'Лечение'],
                'type' => 'full',
            ],
            [
                'title' => 'Фармацевт',
                'industry_slug' => 'healthcare',
                'salary_start' => 1800,
                'salary_end' => 2800,
                'description' => 'Продажа лекарств и консультации.',
                'benefits' => 'Стабильная зарплата.',
                'responsibility' => 'Консультирование покупателей, учет препаратов.',
                'qualifications' => 'Фармацевтическое образование.',
                'experience' => '1 год',
                'education' => 'Среднее специальное',
                'skills' => ['Знание лекарств', 'Консультирование'],
                'type' => 'full',
            ],
            // Construction vacancies (4 templates)
            [
                'title' => 'Бригадир строительной бригады',
                'industry_slug' => 'construction',
                'salary_start' => 3500,
                'salary_end' => 5000,
                'description' => 'Руководство строительной бригадой.',
                'benefits' => 'Жилье на объекте, питание.',
                'responsibility' => 'Координация рабочих, контроль качества.',
                'qualifications' => 'Опыт в строительстве, организаторские навыки.',
                'experience' => '3 года',
                'education' => 'Среднее',
                'skills' => ['Строительство', 'Управление бригадой'],
                'type' => 'full',
            ],
            [
                'title' => 'Каменщик',
                'industry_slug' => 'construction',
                'salary_start' => 2500,
                'salary_end' => 3500,
                'description' => 'Кладка кирпича и блоков на стройке.',
                'benefits' => 'Жилье, питание.',
                'responsibility' => 'Выполнение кладочных работ.',
                'qualifications' => 'Опыт в кладке, физическая выносливость.',
                'experience' => '2 года',
                'education' => 'Среднее',
                'skills' => ['Кладка', 'Строительство'],
                'type' => 'full',
            ],
            [
                'title' => 'Электрик',
                'industry_slug' => 'construction',
                'salary_start' => 2800,
                'salary_end' => 4000,
                'description' => 'Монтаж электропроводки.',
                'benefits' => 'Стабильная зарплата.',
                'responsibility' => 'Установка и ремонт электросистем.',
                'qualifications' => 'Электротехническое образование.',
                'experience' => '2 года',
                'education' => 'Среднее специальное',
                'skills' => ['Электромонтаж', 'Электрика'],
                'type' => 'full',
            ],
            [
                'title' => 'Сантехник',
                'industry_slug' => 'construction',
                'salary_start' => 2500,
                'salary_end' => 3500,
                'description' => 'Монтаж и ремонт сантехники.',
                'benefits' => 'Гибкий график.',
                'responsibility' => 'Установка труб, ремонт сантехнического оборудования.',
                'qualifications' => 'Опыт работы сантехником.',
                'experience' => '2 года',
                'education' => 'Среднее',
                'skills' => ['Сантехника', 'Монтаж'],
                'type' => 'full',
            ],
            // Finance vacancies (4 templates)
            [
                'title' => 'Бухгалтер',
                'industry_slug' => 'finance&accounting',
                'salary_start' => 2000,
                'salary_end' => 3000,
                'description' => 'Ведение бухгалтерской документации.',
                'benefits' => 'Стабильная зарплата, обучение.',
                'responsibility' => 'Обработка счетов, работа в 1С.',
                'qualifications' => 'Знание бухгалтерии, владение 1С.',
                'experience' => '1 год',
                'education' => 'Среднее специальное',
                'skills' => ['1С', 'Бухучет'],
                'type' => 'full',
            ],
            [
                'title' => 'Финансовый консультант',
                'industry_slug' => 'finance&accounting',
                'salary_start' => 2500,
                'salary_end' => 4000,
                'description' => 'Консультации по финансовому планированию.',
                'benefits' => 'Бонусы за результаты, обучение.',
                'responsibility' => 'Работа с клиентами, анализ финансов.',
                'qualifications' => 'Знание финансов, навыки общения.',
                'experience' => '2 года',
                'education' => 'Высшее экономическое',
                'skills' => ['Финансовое планирование', 'Консультации'],
                'type' => 'full',
            ],
            [
                'title' => 'Кассир',
                'industry_slug' => 'finance&accounting',
                'salary_start' => 1500,
                'salary_end' => 2000,
                'description' => 'Работа с наличными и безналичными платежами.',
                'benefits' => 'Стабильная зарплата, сменный график.',
                'responsibility' => 'Прием и выдача денег.',
                'qualifications' => 'Навыки работы с кассой.',
                'experience' => 'Без опыта',
                'education' => 'Среднее',
                'skills' => ['Кассовая дисциплина', 'Работа с клиентами'],
                'type' => 'full',
            ],
            [
                'title' => 'Аудитор',
                'industry_slug' => 'finance&accounting',
                'salary_start' => 3000,
                'salary_end' => 4500,
                'description' => 'Проведение финансовых аудитов.',
                'benefits' => 'Бонусы, обучение.',
                'responsibility' => 'Проверка финансовой отчетности.',
                'qualifications' => 'Опыт в аудите, знание стандартов.',
                'experience' => '3 года',
                'education' => 'Высшее экономическое',
                'skills' => ['Аудит', 'Финансовый анализ'],
                'type' => 'full',
            ],
            // Agriculture vacancies (4 templates)
            [
                'title' => 'Фермер-агроном',
                'industry_slug' => 'agricultural',
                'salary_start' => 2000,
                'salary_end' => 3000,
                'description' => 'Выращивание сельскохозяйственных культур.',
                'benefits' => 'Жилье, питание.',
                'responsibility' => 'Уход за посевами, сбор урожая.',
                'qualifications' => 'Опыт в сельском хозяйстве.',
                'experience' => '2 года',
                'education' => 'Среднее',
                'skills' => ['Сельское хозяйство', 'Агрономия'],
                'type' => 'full',
            ],
            [
                'title' => 'Работник фермы',
                'industry_slug' => 'agricultural',
                'salary_start' => 1500,
                'salary_end' => 2000,
                'description' => 'Работа на ферме по уходу за растениями.',
                'benefits' => 'Жилье, питание.',
                'responsibility' => 'Полив, уход за животными, уборка.',
                'qualifications' => 'Физическая выносливость.',
                'experience' => 'Без опыта',
                'education' => 'Среднее',
                'skills' => ['Сельское хозяйство', 'Физическая работа'],
                'type' => 'full',
            ],
            [
                'title' => 'Тракторист',
                'industry_slug' => 'agricultural',
                'salary_start' => 2000,
                'salary_end' => 3000,
                'description' => 'Работа на тракторе для обработки полей.',
                'benefits' => 'Жилье, питание.',
                'responsibility' => 'Обработка полей, обслуживание техники.',
                'qualifications' => 'Удостоверение тракториста.',
                'experience' => '1 год',
                'education' => 'Среднее',
                'skills' => ['Трактор', 'Сельское хозяйство'],
                'type' => 'full',
            ],
            [
                'title' => 'Ветеринар',
                'industry_slug' => 'agricultural',
                'salary_start' => 2500,
                'salary_end' => 3500,
                'description' => 'Лечение сельскохозяйственных животных.',
                'benefits' => 'Стабильная зарплата.',
                'responsibility' => 'Осмотр и лечение животных.',
                'qualifications' => 'Ветеринарное образование.',
                'experience' => '2 года',
                'education' => 'Высшее',
                'skills' => ['Ветеринария', 'Животноводство'],
                'type' => 'full',
            ],
            // Tourism vacancies (4 templates)
            [
                'title' => 'Администратор гостевого дома',
                'industry_slug' => 'tourism&hotels',
                'salary_start' => 1500,
                'salary_end' => 2500,
                'description' => 'Обслуживание гостей в гостевом доме.',
                'benefits' => 'Проживание, питание.',
                'responsibility' => 'Прием гостей, организация их пребывания.',
                'qualifications' => 'Знание таджикского и русского языков.',
                'experience' => 'Без опыта',
                'education' => 'Среднее',
                'skills' => ['Гостеприимство', 'Обслуживание клиентов'],
                'type' => 'full',
            ],
            [
                'title' => 'Гид по Памиру',
                'industry_slug' => 'tourism&hotels',
                'salary_start' => 2000,
                'salary_end' => 3500,
                'description' => 'Проведение экскурсий по Памирским горам.',
                'benefits' => 'Проживание, питание, бонусы.',
                'responsibility' => 'Проведение экскурсий, обеспечение безопасности.',
                'qualifications' => 'Знание английского или русского.',
                'experience' => '1 год',
                'education' => 'Среднее',
                'skills' => ['Экскурсии', 'Коммуникация'],
                'type' => 'part',
            ],
            [
                'title' => 'Повар в ресторане',
                'industry_slug' => 'tourism&hotels',
                'salary_start' => 2000,
                'salary_end' => 3000,
                'description' => 'Приготовление блюд в ресторане.',
                'benefits' => 'Питание, стабильная зарплата.',
                'responsibility' => 'Приготовление блюд, соблюдение гигиены.',
                'qualifications' => 'Опыт работы поваром.',
                'experience' => '2 года',
                'education' => 'Среднее специальное',
                'skills' => ['Кулинария', 'Приготовление пищи'],
                'type' => 'full',
            ],
            [
                'title' => 'Официант',
                'industry_slug' => 'tourism&hotels',
                'salary_start' => 1200,
                'salary_end' => 1800,
                'description' => 'Обслуживание посетителей ресторана.',
                'benefits' => 'Чаевые, питание.',
                'responsibility' => 'Прием заказов, обслуживание столов.',
                'qualifications' => 'Навыки общения.',
                'experience' => 'Без опыта',
                'education' => 'Среднее',
                'skills' => ['Обслуживание клиентов', 'Коммуникация'],
                'type' => 'full',
            ],
            // Logistics vacancies (3 templates)
            [
                'title' => 'Водитель грузового автомобиля',
                'industry_slug' => 'logistics&transport',
                'salary_start' => 2500,
                'salary_end' => 3500,
                'description' => 'Перевозка грузов по Таджикистану.',
                'benefits' => 'Компенсация топлива, питание.',
                'responsibility' => 'Доставка грузов, соблюдение сроков.',
                'qualifications' => 'Водительские права категории C.',
                'experience' => '3 года',
                'education' => 'Среднее',
                'skills' => ['Вождение', 'Логистика'],
                'type' => 'full',
            ],
            [
                'title' => 'Экспедитор',
                'industry_slug' => 'logistics&transport',
                'salary_start' => 1800,
                'salary_end' => 2500,
                'description' => 'Организация доставки грузов.',
                'benefits' => 'Стабильная зарплата.',
                'responsibility' => 'Координация поставок, работа с документами.',
                'qualifications' => 'Навыки планирования.',
                'experience' => '1 год',
                'education' => 'Среднее',
                'skills' => ['Логистика', 'Планирование'],
                'type' => 'full',
            ],
            [
                'title' => 'Кладовщик',
                'industry_slug' => 'logistics&transport',
                'salary_start' => 1500,
                'salary_end' => 2000,
                'description' => 'Учет товаров на складе.',
                'benefits' => 'Стабильная зарплата.',
                'responsibility' => 'Прием и отпуск товаров, инвентаризация.',
                'qualifications' => 'Внимательность, ответственность.',
                'experience' => 'Без опыта',
                'education' => 'Среднее',
                'skills' => ['Складской учет', 'Инвентаризация'],
                'type' => 'full',
            ],
            // Marketing vacancies (3 templates)
            [
                'title' => 'SMM-менеджер',
                'industry_slug' => 'marketing&ads',
                'salary_start' => 2000,
                'salary_end' => 3500,
                'description' => 'Ведение социальных сетей компании.',
                'benefits' => 'Удалённая работа, гибкий график.',
                'responsibility' => 'Создание контента, работа с подписчиками.',
                'qualifications' => 'Знание SMM, креативность.',
                'experience' => '1 год',
                'education' => 'Среднее',
                'skills' => ['SMM', 'Контент-маркетинг'],
                'type' => 'remote',
            ],
            [
                'title' => 'Менеджер по продажам',
                'industry_slug' => 'marketing&ads',
                'salary_start' => 1800,
                'salary_end' => 3000,
                'description' => 'Поиск клиентов и продажа продукции.',
                'benefits' => 'Бонусы от продаж.',
                'responsibility' => 'Работа с клиентами, заключение договоров.',
                'qualifications' => 'Навыки общения, активность.',
                'experience' => '1 год',
                'education' => 'Среднее',
                'skills' => ['Продажи', 'Переговоры'],
                'type' => 'full',
            ],
            [
                'title' => 'Дизайнер',
                'industry_slug' => 'marketing&ads',
                'salary_start' => 2500,
                'salary_end' => 4000,
                'description' => 'Создание графических материалов.',
                'benefits' => 'Удалённая работа.',
                'responsibility' => 'Разработка дизайна для рекламы.',
                'qualifications' => 'Знание Adobe Photoshop, Illustrator.',
                'experience' => '2 года',
                'education' => 'Среднее специальное',
                'skills' => ['Photoshop', 'Illustrator', 'Дизайн'],
                'type' => 'remote',
            ],
            // Production vacancies (3 templates)
            [
                'title' => 'Оператор станка',
                'industry_slug' => 'production',
                'salary_start' => 2000,
                'salary_end' => 2800,
                'description' => 'Работа на производственном оборудовании.',
                'benefits' => 'Стабильная зарплата.',
                'responsibility' => 'Обслуживание станков, контроль качества.',
                'qualifications' => 'Опыт работы на станках.',
                'experience' => '1 год',
                'education' => 'Среднее',
                'skills' => ['Работа на станках', 'Производство'],
                'type' => 'full',
            ],
            [
                'title' => 'Контролер качества',
                'industry_slug' => 'production',
                'salary_start' => 1800,
                'salary_end' => 2500,
                'description' => 'Контроль качества продукции.',
                'benefits' => 'Стабильная зарплата.',
                'responsibility' => 'Проверка продукции, ведение документации.',
                'qualifications' => 'Внимательность к деталям.',
                'experience' => '1 год',
                'education' => 'Среднее',
                'skills' => ['Контроль качества', 'Документооборот'],
                'type' => 'full',
            ],
            [
                'title' => 'Инженер-технолог',
                'industry_slug' => 'production',
                'salary_start' => 3000,
                'salary_end' => 4500,
                'description' => 'Разработка производственных процессов.',
                'benefits' => 'Обучение, карьерный рост.',
                'responsibility' => 'Оптимизация производства.',
                'qualifications' => 'Техническое образование.',
                'experience' => '3 года',
                'education' => 'Высшее техническое',
                'skills' => ['Технология производства', 'Инжиниринг'],
                'type' => 'full',
            ],
            // Public service vacancies (2 templates)
            [
                'title' => 'Специалист по госзакупкам',
                'industry_slug' => 'public_service',
                'salary_start' => 2500,
                'salary_end' => 3500,
                'description' => 'Организация закупок для государственных учреждений.',
                'benefits' => 'Стабильная зарплата, соцпакет.',
                'responsibility' => 'Подготовка документации, участие в тендерах.',
                'qualifications' => 'Знание законодательства о закупках.',
                'experience' => '2 года',
                'education' => 'Высшее',
                'skills' => ['Госзакупки', 'Документооборот'],
                'type' => 'full',
            ],
            [
                'title' => 'Юрист',
                'industry_slug' => 'public_service',
                'salary_start' => 2800,
                'salary_end' => 4000,
                'description' => 'Юридическое сопровождение.',
                'benefits' => 'Стабильная зарплата.',
                'responsibility' => 'Консультации, подготовка документов.',
                'qualifications' => 'Юридическое образование.',
                'experience' => '2 года',
                'education' => 'Высшее',
                'skills' => ['Юриспруденция', 'Документооборот'],
                'type' => 'full',
            ],
            // Other vacancies (4 templates)
            [
                'title' => 'Портной',
                'industry_slug' => 'other',
                'salary_start' => 1500,
                'salary_end' => 2500,
                'description' => 'Пошив национальной одежды.',
                'benefits' => 'Гибкий график.',
                'responsibility' => 'Пошив, ремонт одежды.',
                'qualifications' => 'Навыки шитья.',
                'experience' => '1 год',
                'education' => 'Среднее',
                'skills' => ['Шитье', 'Работа с клиентами'],
                'type' => 'full',
            ],
            [
                'title' => 'Парикмахер',
                'industry_slug' => 'other',
                'salary_start' => 1500,
                'salary_end' => 2500,
                'description' => 'Стрижка и укладка волос.',
                'benefits' => 'Чаевые, гибкий график.',
                'responsibility' => 'Обслуживание клиентов.',
                'qualifications' => 'Навыки парикмахера.',
                'experience' => '1 год',
                'education' => 'Среднее специальное',
                'skills' => ['Парикмахерское дело', 'Обслуживание клиентов'],
                'type' => 'full',
            ],
            [
                'title' => 'Уборщик/Уборщица',
                'industry_slug' => 'other',
                'salary_start' => 1000,
                'salary_end' => 1500,
                'description' => 'Уборка помещений.',
                'benefits' => 'Стабильная зарплата.',
                'responsibility' => 'Уборка офисов, поддержание чистоты.',
                'qualifications' => 'Ответственность.',
                'experience' => 'Без опыта',
                'education' => 'Среднее',
                'skills' => ['Уборка', 'Чистота'],
                'type' => 'full',
            ],
            [
                'title' => 'Охранник',
                'industry_slug' => 'other',
                'salary_start' => 1500,
                'salary_end' => 2200,
                'description' => 'Обеспечение безопасности объекта.',
                'benefits' => 'Сменный график.',
                'responsibility' => 'Контроль доступа, патрулирование.',
                'qualifications' => 'Физическая подготовка.',
                'experience' => 'Без опыта',
                'education' => 'Среднее',
                'skills' => ['Охрана', 'Безопасность'],
                'type' => 'full',
            ],
        ];

        $locations = ['Душанбе', 'Худжанд', 'Куляб', 'Бохтар', 'Гиссар', 'Хорог', 'Пенджикент', 'Курган-Тюбе', 'Рашт', 'Исфара'];

        // Create 100+ vacancies by repeating templates and varying them
        $vacanciesCreated = 0;
        $targetVacancies = 100;

        while ($vacanciesCreated < $targetVacancies) {
            foreach ($vacancyTemplates as $template) {
                if ($vacanciesCreated >= $targetVacancies) break;

                $industry = Industry::where('slug', $template['industry_slug'])->first();
                if (!$industry) continue;

                $employerId = $employerIds[array_rand($employerIds)];
                $location = $locations[array_rand($locations)];

                // Add variation to salary
                $salaryVariation = rand(-200, 200);

                Vacancy::create([
                    'employer_id' => $employerId,
                    'title' => $template['title'],
                    'salary_type' => 'money',
                    'salary_start' => max(1000, $template['salary_start'] + $salaryVariation),
                    'salary_end' => max(1500, $template['salary_end'] + $salaryVariation),
                    'location' => $location,
                    'industry_id' => $industry->id,
                    'description' => $template['description'],
                    'benefits' => $template['benefits'],
                    'responsibility' => $template['responsibility'],
                    'qualifications' => $template['qualifications'],
                    'experience' => $template['experience'],
                    'education' => $template['education'],
                    'skills' => $template['skills'],
                    'type' => $template['type'],
                    'status' => 'active',
                ]);

                $vacanciesCreated++;
            }
        }
    }
}
